---
title: "Prepare data"
author: "Stefano Coretta"
format: html
---

```{r}
#| label: setup

library(tidyverse)
library(phonetisr)
```

```{r}
ipa <- read_csv("ipa.csv")

old <- ipa$symbol
new <- ipa$ipa

names(new) <- old
```


```{r}
mrc_db <- read_fwf(
  "1054/mrc2.dct",
  fwf_widths(
    c(2, 2, 1, 5, 2, 3, 6, 4, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, NA),
    c("nlet", "nphon", "nsyl", "kf_freq", "kf_ncats", "kf_nsamp", "tl_freq", "brown_freq", "fam", "conc", "imag", "meanc", "meanp", "aoa", "tq2", "wtype", "pdwtype", "alphsyl", "status", "var", "cap", "irreg", "last_col")
  ),
  col_types = "nnnnnnnnnnnnnnccccccccc"
) |> 
  separate(
    last_col,
    c("word", "phon", "dphon", "stress"),
    sep = "\\|"
  ) |> 
  mutate(
    dphon = str_remove_all(dphon, "\\s?Q|\\s?2|\\s?2 Q"),
    ipa = str_replace_all(dphon, new),
    ipa = str_replace_all(ipa, "'", "ˈ"),
    ipa = str_replace_all(ipa, ",", "ˌ"),
    ipa_syl = str_replace_all(phon, new),
    ipa_syl = str_replace_all(ipa_syl, "/", "."),
    phones = phonetise(ipa, multi = c("tʃ", "dʒ", "aɪ", "eɪ", "oɪ", "eə", "ɪə", "aʊ", "əʊ"), diacritics = TRUE)
  )
```

```{r}
usethis::use_data(mrc_db, overwrite = TRUE)
```

